ScrumGame/ScrumGame/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ScrumGame.Models;
using ScrumGame.Services;

namespace ScrumGame.Controllers
{
	/// <summary>
	/// Singleton pattern implemented from ("Second version - simple thread-safety"):
	///	https://csharpindepth.com/Articles/Singleton
	/// </summary>	
	public class GameController : Controller
    {
		//private static GameControllerSingleton instance = null;

		//private static readonly object padlock = new object();

		public int MinPlayerCount { get { return 2; } }

		public int MaxPlayerCount { get { return 6; } }

		public int PlayerCount { get { return this.Players.Count; } }

		public List<Player> Players { get; private set; }

		public Player Winner { get; private set; }

		private readonly IPlayerRepository _playerRepo;

		/// <summary>
		/// Constructs the instance of the GameControllerSingleton object
		/// </summary>
		public GameController(IPlayerRepository playerRepo)
		{
			_playerRepo = playerRepo;
			this.Players = new List<Player>() { new Player("Alec H", new DateTime(1997, 11, 19))};
			if (InitializeGame() == 1)
			{
				//no
/*				while (true)//????????????????
				{
					//Game Loop goes here
					
					// End the turn here
					GiveWorkshopTokens();
					
					//Ends the Game if a winner has been declared
					if (this.Winner != null)
						break;
				}
*/				//Do stuff for winner here
			}
			else
			{
				//throw error
			}
		}

		public async Task<IActionResult> Index()
        {
			var model = await _playerRepo.ReadAllAsync();
			return View(model);
        }

		/// <summary>
		/// Increments the number of completed user stories for player p and checks if they won.
		/// </summary>
		/// <param name="p"></param>
		/// <returns></returns>
		public Player CompletedUserStory(Player p)
		{
			p.UseCasesCompleted++;
			return WinByUseCasesCheck(p);
		}


		/// <summary>
		/// Takes a list of Players (optional) or All the players to give a workshop token
		/// </summary>
		/// <param name="ps">List of players to give workshop tokens to</param>
		/// <returns></returns>
		public int GiveWorkshopTokens(List<Player> ps = null)
		{
			List<Player> players = ps ?? this.Players;
			foreach (var p in players)
				p.WorkshopTokens++;

			return 1;
		}

		/// <summary>
		/// Initalizes the setup of the game...
		/// </summary>
		/// <returns>integer representing if the game was successfully setup or not</returns>
		public int InitializeGame()
		{
			return 1;
		}

		/// <summary>
		/// Checks if a Player has met the WinByUseCases condition. If more than 1 at the same time, throws an error.
		/// Do not wait till end of round to call this or we will encounter errors.
		/// </summary>
		/// <returns></returns>
		public Player WinByUseCasesCheck(Player player=null)
        {
			Player winner = null;
			//If Player has been given, only check that player
			if (player != null) 
			{
				if (player.UseCasesRemaining == 0)
					winner = player;
				return winner;
			}

			foreach (var p in this.Players )
			{
				if (p.UseCasesRemaining == 0)
				{
					if (winner != null)
					{
						//Throw some kind of error - this should never be triggered though
					}
					winner = p;
				}
			}
			return winner;
        }
		/// <summary>
		/// Part of the singleton design patern, used to aquire the instance of the GameController
		/// </summary>
		/*
		public static GameControllerSingleton Instance
		{
			get
			{
				lock (padlock)
				{
					if (instance == null)
					{
						instance = new GameControllerSingleton();
					}
					return instance;
				}
			}
		}
		*/

		/// <summary>
		/// Commented this and the AddPlayer methods out temporarily - Subject to removal. - Adam
		/// </summary>
		/// <returns></returns>
		// public IActionResult PlayersList()
        // {
		// 	var model = _playerRepo.ReadAll();
        //     return View(model);
        // }

		//public IActionResult AddPlayer()
  //      {
		//	return View();
  //      }

		//[HttpPost]
		//public IActionResult AddPlayer(Player p)
		//{
		//	if (ModelState.IsValid)
		//	{
		//		if (Players.Count < this.MaxPlayerCount)
		//		{
		//			p.Money = GetAverageMoney();
		//			_playerRepo.Create(p);
		//			return RedirectToAction("PlayersList");
		//		}
		//		else
		//			return View(p);
		//	}
		//	else
  //          {
		//		return View(p);
		//	}
		//}

		public int GetAverageMoney(int starterMoney=500) 
		{
			int sum = 0, count;

			for (count = 0; count < Players.Count; count++)
				sum += Players[count].Money;

			return ( count > 0 ) ? ( sum / count ) : starterMoney;	//Returns average if there is more than 0 players.
		}

		/// <summary>
		/// Removes a player
		/// </summary>
		/// <param name="p">The player to remove</param>
		/// <returns>Integer representing if the game can still continue after removing the player</returns>
		public int RemovePlayer(Player p)
		{
			if (Players.Count > this.MinPlayerCount)
			{
				Players.Remove(p);
				return 0;
			}
			else
			{
				Players.Remove(p);
				return -1;
			}
				
		}


		public List<Player> DeterminePlayerOrder()
		{
			int[] OrderIndex = new int[this.PlayerCount];
			Player[] PlayerOrder = new Player[this.PlayerCount];

			/* fills with defaults */
			for (int i = 0; i < this.PlayerCount; i++)
				OrderIndex[i] = i;

			/* find index of winner */
			Player winner = RollOffCompetition(this.Players);
			int WinnerNum = Array.IndexOf(this.Players.ToArray(), winner);
			
			/* loops through remaining indices */
			OrderIndex[0] = WinnerNum;
			int CurrentLoserNum = (WinnerNum < this.PlayerCount-1) ? WinnerNum + 1: 0;
			for (int i = 1; i < this.PlayerCount; i++)
			{
				if (CurrentLoserNum == this.PlayerCount - 1)
					CurrentLoserNum = 0;
				else
					CurrentLoserNum++;

				OrderIndex[i] = CurrentLoserNum;
			}

			/* stores each player based on index */
			foreach (var index in OrderIndex)
				PlayerOrder[index] = this.Players[index];

			return PlayerOrder.ToList();
		}
		
		//TODO: I NEED TO TEST THIS METHOD 
		//PROBABLY NOT WORKING YET DO NOT TRUST THIS
		/*public List<Player> DeterminePlayerOrder()
		{
			Dictionary<Player, int> playerRolls = new Dictionary<Player, int>();

			int maxRoll = int.MinValue;
			foreach (var p in Players)
			{
				int pRoll = p.RollDice(1)[0];
				if (pRoll > maxRoll)
					maxRoll = pRoll;
				playerRolls.Add(p, pRoll);
			}
			
			//this could be removed i guess?? since we only really care about who is going first
			var playerOrder = from entry in playerRolls orderby entry.Value ascending select entry;

			List<Player> firstCompetition = new List<Player>();
			foreach (var p in playerOrder)
			{
				int pRoll = p.Value;
				if (maxRoll == pRoll)
					firstCompetition.Add(p.Key);
			}


			if (firstCompetition.Count > 1)
			{
				//go do a roll off
			}


			this.Players.Clear();

			foreach (var p in playerOrder)
			{
				this.Players.Add(p.Key);
			}

			return this.Players;
		}*/

		/*struct PlayerCompetitionEntry
		{
			public Player player;
			public bool disqualified;
		}*/

		//TODO: I NEED TO TEST THIS METHOD
		//PROBABLY NOT WORKING YET DO NOT TRUST THIS
		public Player RollOffCompetition(List<Player> players=null)
		{
			/*PlayerCompetitionEntry[] entries = new PlayerCompetitionEntry[players.Count];
			for (int i = 0; i < players.Count; i++)
			{
				PlayerCompetitionEntry entry;
				entry.player = players[i];
				entry.disqualified = false;
				entries[i] = entry;
			}*/
			// Takes an optional parameter (or uses all playeres) and makes a deep copy of it using LINQ. 
			/* https://stackoverflow.com/questions/14007405/how-create-a-new-deep-copy-clone-of-a-listt */
			List<Player> RollingPlayers = ( players ?? this.Players )
						.Select(player => new Player(player.Name, Convert.ToDateTime(player.DoB)))
						.ToList();
					
			int difference = 0;
			int maxRoll = int.MinValue;
			int currentRoll = int.MinValue;
			while (RollingPlayers.Count > 1)
			{
				for (int i = 0; i < RollingPlayers.Count;)
				{
					currentRoll = RollingPlayers[i].RollDice(1)[0];

					if (currentRoll > maxRoll)
						maxRoll = currentRoll;

					difference = currentRoll - maxRoll;

					if (difference != 0)
						RollingPlayers.RemoveAt(i);
					else
						i++;
				}
			}
			/*while (difference == 0)
			{
				for(int i = 0; i < entries.Length; i++)
				{
					if (!entries[i].disqualified)
					{
						currentRoll = entries[i].player.RollDice(1)[0];

						if (currentRoll > maxRoll)
							maxRoll = currentRoll;

						difference = currentRoll - maxRoll;

						if (difference != 0)
							entries[i].disqualified = true;
					}
				}
			}*/

			//return (from p in entries where !p.disqualified select p.player).First();
			return RollingPlayers[0];
		}
    }
}

ScrumGame/ScrumGame/Controllers/PlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using ScrumGame.Models;
using ScrumGame.Services;

namespace ScrumGame.Controllers
{
    public class PlayersController : Controller
    {
        private readonly IPlayerRepository _playerRepo;

        public PlayersController(IPlayerRepository playerRepo)
        {
            _playerRepo = playerRepo;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Player player)
        {
            var newPlayer = await _playerRepo.CreateAsync(player);
            //return Json(new { newPlayer.Id });
            
            return RedirectToAction("Index", "Game");
        }

        public async Task<IActionResult> PlayerRow(int id)
        {
            var player = await _playerRepo.ReadAsync(id);
            return PartialView("/Views/Home/_PlayerRow.cshtml", player);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await _playerRepo.DeleteAsync(id);
            //return Json(new { id });
            return RedirectToAction("Index", "Game");

        }
    }
}

ScrumGame/ScrumGame/Views/Game/AddPlayer.cshtml
@model ScrumGame.Models.Player
@using ScrumGame.Models

@{
    ViewData["Title"] = "Create A Player";
    Layout = "~/Views/Shared/_Layout.cshtml";
 }

<h1>Create</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AddPlayer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoB" class="control-label"></label>
                <input asp-for="DoB" class="form-control" />
                <span asp-validation-for="DoB" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="AddPlayer" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="PlayersList" asp-controller="Game">Back to Players' List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ScrumGame/ScrumGame/Views/Game/Index.cshtml
@model IEnumerable<ScrumGame.Models.Player>

@{ 
    ViewData["Title"] = "Scrum Game";

    var player = new ScrumGame.Models.Player() { Name = "", DoB = "1/1/1999" };
    
}
<div id="alertArea" class="alert alert-warning" role="alert" style="display:none">
        <span id="messageArea"></span>
    <button id="alertCloseBtn" type="button" class="close" aria-label="Close">
            <span aria-hidden="true">&times;</span>
    </button>
</div>

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createPlayerModal">Add New Player</button>
<partial name="_PlayerModal.cshtml" model="player" />

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#listModal">View Player List</button>
<partial name="_ListModal.cshtml" />


@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoB)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody id="tbody-players">
        @foreach (var item in Model)
        {
            <partial name="_PlayerRow" model="@item" />
        }
    </tbody>
</table>*@

@section scripts{
    @*<script src="~/lib/signalr/dist/browser/signalr.js"></script>*@
    <script src="~/js/gameIndex.js"></script>
}

ScrumGame/ScrumGame/Views/Game/PlayersList.cshtml
@model IEnumerable<ScrumGame.Models.Player>

@{
    ViewData["Title"] = "All Players";
}

<h1>@ViewData["Title"]</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Date of Birth
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var player in Model)
		{
            <tr>
                <td>
					@Html.DisplayFor(modelItem => player.Name)
				</td>
                <td>
					@Html.DisplayFor(modelItem => player.DoB)
				</td>
			</tr>
        }
    </tbody>
</table>

<div>
    <a asp-action="AddPlayer" asp-controller="Game">Add a Player</a>
</div>

ScrumGame/ScrumGame/Views/Game/_ListModal.cshtml
@model IEnumerable<ScrumGame.Models.Player>
@{
}

<div class="modal fade" id="listModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div id="mainContent" class="modal-content col-sm-9">

            <div class="modal-header">
                <h5 class="modalTitle" id="listModalTitle">Create Player</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>

            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Id)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.DoB)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="tbody-players">
                        @foreach (var item in Model)
                        {
                            <partial name="_PlayerRow" model="@item"/> 
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/js/gameIndex.js"></script>
}

ScrumGame/ScrumGame/Views/Game/_PlayerModal.cshtml
@model ScrumGame.Models.Player
<div class="modal fade" id="createPlayerModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div id="mainContent" class="modal-content col-sm-9">
            <form id="createPlayerForm" asp-controller="Players" asp-action="Create">

                <div class="modal-header">
                    <h5 class="modalTitle" id="createPlayerModalTitle">Add New Player</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>

                </div>

                <div class="modal-body">
                    <div class="form-group row">
                        <label asp-for="@Model.Name" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="@Model.Name" class="form-control" placeholder="Name" />
                            <span asp-validation-for="@Model.Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label asp-for="@Model.DoB" class="col-sm-2 col-form-label"></label>
                        <div class="col-sm-10">
                            <input asp-for="@Model.DoB" class="form-control" placeholder="Name" />
                            <span asp-validation-for="@Model.DoB" class="text-danger"></span>
                        </div>
                    </div>

                </div>

                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="reset" class="btn btn-secondary">Clear</button>
                </div>
            </form>
        </div>
    </div>
</div>

ScrumGame/ScrumGame/Views/Game/_PlayerRow.cshtml
@model Player
<tr id="row-@Model.Id">
    <td>
        @Html.DisplayFor(modelItem => Model.Id)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => Model.DoB)
    </td>
    <td>
        <!--<a asp-action="Delete" asp-controller="Players" asp-route-id="@Model.Id" class="btn btn-danger removeBtn">Remove</a>-->
        @using (Html.BeginForm("Delete", "Players", FormMethod.Post))
        {
			@Html.Hidden("id", Model.Id)
			<input type="image" src="~/images/trash.svg" width="24" height="24"/>
		}
    </td>
</tr>